name: Release Voyager

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        os: [win, linux, osx]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Extract Semver
        id: semver_parser
        run: |
          semver=${TAG#"refs/tags/v"}
          semver=${semver%"-voyager"}

          echo ::set-output name=semver::$semver
        env:
          TAG: ${{ github.ref }}

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Release for OS
        run: |
          mkdir bin
          dotnet publish -r ${{matrix.os}}-x64 --self-contained false -p:PublishSingleFile=true -o bin -c Release -p:Version=${{ steps.semver_parser.outputs.semver }} Honeydew/Honeydew.csproj

      - name: Prepare Assets
        run: |
          mkdir -p ${{matrix.os}}
          rm bin/*.pdb
          cp -R bin/* ${{matrix.os}}

      - name: Create Archive
        run: zip -r honeydew-${{ matrix.os }}.zip ${{matrix.os}}

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: honeydew-${{ matrix.os }}.zip
          path: honeydew-${{ matrix.os }}.zip

  release-and-upload:
    name: Release Honeydew for Voyager
    runs-on: ubuntu-latest
    needs: build-and-publish
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download all artifacts
        uses: actions/download-artifact@v2

      - name: Extract Semver
        id: semver_parser
        run: |
          semver=${TAG#"refs/tags/v"}
          semver=${semver%"-voyager"}

          echo ::set-output name=semver::$semver
        env:
          TAG: ${{ github.ref }}

      - name: Prepare Assets
        run: |
          mkdir -p honeydew/results
          mkdir -p honeydew/bin

          cp README.md honeydew/README.md
          cp instrument.yml honeydew/instrument.yml

          unzip ./honeydew-win.zip/honeydew-win.zip -d honeydew/bin
          unzip ./honeydew-linux.zip/honeydew-linux.zip -d honeydew/bin
          unzip ./honeydew-osx.zip/honeydew-osx.zip -d honeydew/bin

          ls -al -R honeydew

          chmod +x honeydew/bin/win/Honeydew.exe
          chmod +x honeydew/bin/linux/Honeydew
          chmod +x honeydew/bin/osx/Honeydew

      - name: Zip Voyager Release
        run: zip -rl honeydew-voyager.zip honeydew

      - name: Prepare Release Notes
        run: touch ${{ github.workspace }}/releaseNotes/v${{ steps.semver_parser.outputs.semver }}.md

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          name: Honeydew ${{ steps.semver_parser.outputs.semver }}
          body_path: ${{ github.workspace }}/releaseNotes/v${{ steps.semver_parser.outputs.semver }}.md
          body: ""
          prerelease: false
          draft: false
          files: honeydew-voyager.zip
