name: Release Voyager

on:
  push:
    tags:
      - 'v*-voyager'

jobs:
  release-voyager:
    name: Release Voyager
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'

      - name: Publish for All OS
        run: |
          mkdir bin
          dotnet publish -r win-x64 --self-contained true -p:PublishSingleFile=true -o bin/win -c Release Honeydew/Honeydew.csproj
          dotnet publish -r linux-x64 --self-contained true -p:PublishSingleFile=true -o bin/linux -c Release Honeydew/Honeydew.csproj
          dotnet publish -r osx-x64 --self-contained true -p:PublishSingleFile=true -o bin/osx -c Release Honeydew/Honeydew.csproj

      - name: Prepare Assets
        run: |
          mkdir -p honeydew/results
          cp README.md honeydew/README.md
          rm bin/**/*.pdb
          cp -R bin/* honeydew
          ls -R -al honeydew

      - name: Create Archive
        run: zip -r honeydew.zip honeydew

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Honeydew ${{ github.ref }} (Voyager)
          draft: false
          prerelease: false

      - name: Upload Windows Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./honeydew.zip
          asset_name: honeydew.zip
          asset_content_type: application/zip


  build-and-publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        os: [win, linux]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'

      - name: Release for OS
        run: |
          mkdir bin
          dotnet publish -r ${{matrix.os}}-x64 --self-contained true -p:PublishSingleFile=true -o bin -c Release Honeydew/Honeydew.csproj

      - name: Prepare Assets
        run: |
          mkdir -p ${{matrix.os}}
          rm bin/*.pdb
          cp -R bin/* ${{matrix.os}}

      - name: Create Archive
        run: zip -r honeydew-${{ matrix.os }}.zip ${{matrix.os}}

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: honeydew-${{ matrix.os }}.zip
          path: honeydew-${{ matrix.os }}.zip

  build-publish-and-sign-for-mac:
    name: Build, Publish and Sign (osx)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true


      - name: dotnet publish
        run: |
          mkdir bin
          dotnet publish -r osx-x64 --self-contained true -p:PublishSingleFile=true -o bin -c Release Honeydew/Honeydew.csproj

      - name: Prepare Assets
        run: |
          mkdir -p macos
          rm ./bin/*.pdb
          cp ./bin/Honeydew macos/Honeydew
          chmod +x macos/Honeydew

      - name: Add Cert to Keychain
        uses: apple-actions/import-codesign-certs@v1
        with:
          p12-file-base64: ${{ secrets.MAC_CERT_BASE64 }}
          p12-password: ${{ secrets.MAC_CERT_PASSWORD }}

      - name: Sign Binaries
        run: "sh macSigningScripts/SignMac.sh \"macos/Honeydew\" \"macos/*\" \"Developer ID Application: Andrei Mario Rivis (3L7BS894T6)\" \"macSigningScripts/entitlements.plist\""

      - name: Zip Binary for Notarizing
        run:
          zip -r honeydew-osx.zip macos

      - name: Notarize Binaries
        run: "sh macSigningScripts/Notarize.sh \"mario.rivis@gmail.com\" \"${{ secrets.MAC_DEV_PASSWORD }}\" \"group.org.dxworks\" \"3L7BS894T6\" \"./honeydew-osx.zip\""

      - name: Upload artifact
        uses: actions\upload-artifact@v2
        with:
          name: honeydew-osx.zip
          path: honeydew-osx.zip

  release-and-upload:
    name: Release and Upload
    runs-on: ubuntu-latest
    needs: [build-and-publish, build-publish-and-sign-for-mac]
    steps:

      - uses: actions/checkout@v2

      - name: Download all artifacts
        uses: actions/download-artifact@v2

      - name: List all downloads
        run: |
            echo "Running in directory $PWD"

      - name: Prepare Assets
        run: |
          mkdir -p honeydew/results
          mkdir -p honeydew/bin

          cp README.md honeydew/README.md
          cp instrument.yml honeydew/instrument.yml

          unzip ./honeydew-win.zip/honeydew-win.zip -d honeydew/bin
          unzip ./honeydew-linux.zip/honeydew-linux.zip -d honeydew/bin
          unzip ./honeydew-osx.zip/honeydew-osx.zip -d honeydew/bin

          ls -al -R honeydew

          chmod +x macos/Honeydew

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Honeydew ${{ github.ref }} (Voyager)
          draft: false
          prerelease: false


      - name: Upload Windows Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./honeydew-win.zip/honeydew-win.zip
          asset_name: honeydew-win.zip
          asset_content_type: application/zip

      - name: Upload Linux Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./honeydew-linux.zip/honeydew-linux.zip
          asset_name: honeydew-linux.zip
          asset_content_type: application/zip

      - name: Upload MacOS Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./honeydew-osx.zip/honeydew-osx.zip
          asset_name: honeydew-osx.zip
          asset_content_type: application/zip
