name: Release Voyager

on:
  push:
    tags:
      - 'v*-voyager'

jobs:
  build-and-publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        rid: [win-x64, linux-x64, osx-x64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract Semver
        id: semver_parser
        run: |
          semver=${TAG#"refs/tags/v"}
          semver=${semver%"-voyager"}
          echo "semver=${semver}" >> $GITHUB_OUTPUT
        env:
          TAG: ${{ github.ref }}

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Release for OS
        run: |
          mkdir -p bin
          dotnet publish -r ${{ matrix.rid }} --self-contained false -p:PublishSingleFile=true -o bin -c Release -p:Version=${{ steps.semver_parser.outputs.semver }} Honeydew/Honeydew.csproj

      - name: Prepare Assets
        run: |
          mkdir -p ${{ matrix.rid }}
          rm bin/*.pdb || true
          cp -R bin/* ${{ matrix.rid }}

      - name: Create Archive
        run: zip -r honeydew-${{ matrix.rid }}.zip ${{ matrix.rid }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: honeydew-${{ matrix.rid }}.zip
          path: honeydew-${{ matrix.rid }}.zip

  release-and-upload:
    name: Release Honeydew for Voyager
    runs-on: ubuntu-latest
    needs: build-and-publish
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - name: Extract Semver
        id: semver_parser
        run: |
          semver=${TAG#"refs/tags/v"}
          semver=${semver%"-voyager"}
          echo "semver=${semver}" >> $GITHUB_OUTPUT
        env:
          TAG: ${{ github.ref }}

      - name: Prepare Assets
        run: |
          mkdir -p honeydew/results
          mkdir -p honeydew/bin

          cp README.md honeydew/README.md
          cp instrument.yml honeydew/instrument.yml

          unzip ./honeydew-win-x64.zip/honeydew-win-x64.zip -d honeydew/bin
          unzip ./honeydew-linux-x64.zip/honeydew-linux-x64.zip -d honeydew/bin
          unzip ./honeydew-osx-x64.zip/honeydew-osx-x64.zip -d honeydew/bin

          ls -al -R honeydew

          chmod +x honeydew/bin/win-x64/Honeydew.exe
          chmod +x honeydew/bin/linux-x64/Honeydew
          chmod +x honeydew/bin/osx-x64/Honeydew

      - name: Zip Voyager Release
        run: zip -rl honeydew.zip honeydew

      - name: Prepare Release Notes
        run: touch ${{ github.workspace }}/releaseNotes/v${{ steps.semver_parser.outputs.semver }}.md

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          name: Honeydew ${{ steps.semver_parser.outputs.semver }} (Voyager)
          body_path: ${{ github.workspace }}/releaseNotes/v${{ steps.semver_parser.outputs.semver }}.md
          body: ""
          prerelease: false
          draft: false
          files: honeydew.zip
